version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2024.07.1

    steps:
      - checkout

      - run: chmod +x gradlew
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Accept Android SDK Licenses
          command: (yes || true) | sdkmanager --licenses

      - run:
          name: Run Build
          command: ./gradlew build

      - run:
          name: Run Test
          command: ./gradlew lint test
         
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file