version: 2.1
orbs:
  android: circleci/android@2.4.0
jobs:
  build:
    docker:
      - image: cimg/android:2024.07.1

    steps:
      - checkout

      - name: Gradle Permission
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Download Dependencies
        run: ./gradlew androidDependencies

      - name: Run Build
        run: ./gradlew build

