version: 2.1
orbs:
  android: circleci/android@2.4.0
jobs:
  build:
    docker:
      - image: cimg/android:2024.07.1

    steps:
      - checkout

      - run: chmod +x gradlew
      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

      - run:
          name: Run Build
          command: ./gradlew build


