version: 2.1
orbs:
  android: circleci/android@2.4.0
jobs:
  build:
    docker:
      - image: cimg/android:2024.07.1
    steps:
      - checkout
      -run: chmod +x gradlew
      -run:
        name: Android Gradle Build
        command: /gradlew clean assemble bundle --stacktrace


      -store_artifacts:
        path: app/build/apk
      store_artifacts:
        path: app/build/outputs/